---
title: "Appendices"
---

## 5.1 Appendix A: Listed Materials

|                Material                | Units Per Batch  | Part #  | Source  |
|----------------------------------------|------------------|---------|---------|
|  Innovating Science Arabidopsis Seeds  |   24 seeds    | [S37737](https://www.fishersci.com/shop/products/arabidopsis-seeds/S37737){.external target="_blank"} | Fisher Scientific |
|          MS Basal Salt Medium          |     0.43 g    | [M5524-1L](https://www.sigmaaldrich.com/US/en/product/sigma/m5524?msockid=14c9aa0b1e0460ff3327b9531fd26194){.external target="_blank"} |  Sigma Aldrich |
|            Lab-grade Sucrose           |      2.0 g    |    NA    |  HMC Stockroom |
|   0.1M KOH (prepared from solid KOH)   |  ~300-400 μL  |    NA    |  HMC Stockroom |
|             LB Agar Powder             |     4.36 g    |    NA    |  HMC Stockroom |
|    Triton X-100 (diluted to TX-10)     |      1 mL     | [X100-5ML](https://www.sigmaaldrich.com/US/en/product/sial/x100?msockid=14c9aa0b1e0460ff3327b9531fd26194){.external target="_blank"}    |  Sigma Aldrich |
|              70% Ethanol               |   as needed   |    NA    |  HMC Stockroom |
|    Plant Grow Tent (14inx20inx21in)    |    1   | [NA](https://www.vivosun.com/en-US/vivosun-small-grow-tent-for-aerogarden-p63933466594377747-v145288763577637777){.external target="_blank"} |        Vivosun     |
|           750 mL USB Humidifer         |    1   | [NA](https://www.vivosun.com/en-US/vivosun-aerostream-075-usb-humidifier-p154166259389018256-v154166259389018255){.external target="_blank"} |        Vivosun     |
|         4in Grow Tent Clip Fan         |    1   | [NA](https://www.vivosun.com/en-US/vivosun-aerowave-d4-4-inch-clip-on-fan-compatible-with-growhub-e42-e25-p149779693590506576-v149779693590506557?_lf=buyWith){.external target="_blank"} |        Vivosun     |
|    Bluetooth Hygrometer Thermometer    |    1   | [NA](https://www.vivosun.com/en-US/vivosun-thb1s-thermometer-p147044036718441775-v147044036718441794){.external target="_blank"} |        Vivosun     |
|      Full Spectrum LED Light Board     |    1   | [NA](https://www.vivosun.com/en-US/vivosun-vs1000e-led-grow-light-100w-eco-version-p58820960379615920-v58820960379615910){.external target="_blank"} |        Vivosun     |
| LORDEM Indoor Plant Grow Light (2 Pack)|    1   | [B09CTNVVRR](https://www.amazon.com/Spectrum-Adjustable-Growing-Dimmable-Brightness/dp/B09CTNVVRR/ref=sr_1_1_sspa?crid=3JOEKI92FTC5L&dib=eyJ2IjoiMSJ9.I7VypKtjPhuZgrr9bd48m564CavxfiYXJGWTzHE5LqPCKt1Z7VWOZthF-VxLvWTgQK_cMucxqELbcKkYtQ5v1UFLz7xgzPrthmj0BebyoYSxqLSfB2rFV3bu8jo5tCneQHV_Q8FpgDZJo_-uQ1gIgdwpuDplaYMbrjxUCsI4ok72dybRipShzxluzk3cx5gPiOncbBsnf2-KllsdEblupRxjSxS0A_Dqvt323ueye0L-Czp8CyfteY4-H5-ApsCuVmJaMSIwjEdMj6n3qE31Nugg0tSWOqjhU96n26OgJV8.H4xPh57seos83c3hqqgGXTEVBsQeU7IpScslaHrZ3AM&dib_tag=se&keywords=led%2Bgrow%2Blights%2Bfor%2Bindoor%2Bplants&qid=1751476866&sprefix=led%2Bgrow%2Blight%2Bfor%2Bindoor%2Bplants%2Caps%2C1013&sr=8-1-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&th=1){.external target="_blank"} |        Amazon      |

: Arabidopsis Materials {.striped .hover}


|            Material            | Units  |                     Part #                  |  Source  |
|--------------------------------|--------|---------------------------------------------|----------|
|   Superluminescent Diode (SLD) |    1   | [SLD850s-A20W](https://www.thorlabs.com/thorproduct.cfm?partnumber=SLD880S-A25){.external target="_blank"} | Thorlabs |
|       SLD Driver/Controller    |    1   | [CLD1015](https://www.thorlabs.com/thorproduct.cfm?partnumber=CLD1015){.external target="_blank"} | Thorlabs | Thorlabs |
|  Fiber Polarization Controller |    1   | [FPC033](https://www.thorlabs.com/thorproduct.cfm?partnumber=FPC033){.external target="_blank"} | Thorlabs |
|         2x2 Coupler            |    1   | [PN850R5A2](https://www.thorlabs.com/thorproduct.cfm?partnumber=PN850R5A2){.external target="_blank"} | Thorlabs |
|    Fiber Port Coupler (FPC)    |    2   | [F280APC-850](https://www.thorlabs.com/thorproduct.cfm?partnumber=PN850R5A2){.external target="_blank"} | Thorlabs |
|    Kinematic Pitch Adapter     |    2   | [KAD11F](https://www.thorlabs.com/thorproduct.cfm?partnumber=KAD11F){.external target="_blank"} | Thorlabs |
|   XY Translating Lens Mount    |    2   | [LM1XY](https://www.thorlabs.com/thorproduct.cfm?partnumber=LM1XY){.external target="_blank"} | Thorlabs |
| TIR Retroreflector - A coating |    1   | [PS975M-A](https://www.thorlabs.com/thorproduct.cfm?partnumber=PS975M-A){.external target="_blank"} | Thorlabs |
| TIR Retroreflector - B coating |    1   | [PS975M-B](https://www.thorlabs.com/thorproduct.cfm?partnumber=PN850R5A2){.external target="_blank"} | Thorlabs |
|     Piezo Inertia Actuator     |    1   | [PIA50](https://www.thorlabs.com/thorproduct.cfm?partnumber=PIA50){.external target="_blank"} | Thorlabs |
|     Piezo Stage Controller     |    1   | [KIM101](https://www.thorlabs.com/thorproduct.cfm?partnumber=KIM101){.external target="_blank"} | Thorlabs |
|    Single-Axis Linear Stage    |    3   | [PT1](https://www.thorlabs.com/thorproduct.cfm?partnumber=PT1){.external target="_blank"} | Thorlabs |
|   FC/APC Fiber Adapter Plate   |    1   | [SM1FCA2](https://www.thorlabs.com/thorproduct.cfm?partnumber=SM1FCA2){.external target="_blank"} | Thorlabs |
|       Photodetector (PD)       |    1   | [DET100A2](https://www.thorlabs.com/thorproduct.cfm?partnumber=DET100A2){.external target="_blank"} | Thorlabs |
|    Photodiode Amplifier (PA)   |    1   | [PDA200C](https://www.thorlabs.com/thorproduct.cfm?partnumber=PDA200C){.external target="_blank"} | Thorlabs |
|          NiDAQ Device          |    1   | [NiDAQ SBC-68](https://www.ni.com/docs/en-US/bundle/scb-68-features/resource/372551a.pdf){.external target="_blank"} | National Instruments |

: LCI Materials {.striped .hover}

Note that the materials listed for the LCI setup uses the TIR Retroreflector - A coating for the sample beam and the TIR Retroreflector - B coating for the reference beam. The list of materials does not include general optical table materials such as optical posts and the blackout border material as type and amount were not crucial components of the setup. 

## 5.2 Appendix B: Interference Intensity Derivation

Let's take the interference of two complex electromagnetic waves: a reference wave E~r~ and a sample wave E~s~. 

$$
E_{r}(x,t) = E_{1}cos(k_{1}x - w_{1}t + \phi_{1}) = E_{1}e^{(k_{1}x - w_{1}t + \phi_{1})}
$$

$$
E_{s}(x,t) = E_{2}cos(k_{2}x - w_{2}t + \phi_{2}) = E_{2}e^{(k_{2}x - w_{2}t + \phi_{2})}
$$

The waves superimpose when they interfere.
$$
E_{r}(x,t) + E_{s}(x,t) = E_{1}e^{(k_{1}x - w_{1}t + \phi_{1})} + E_{2}e^{(k_{2}x - w_{2}t + \phi_{2})}
$$

However, what we observe is the square of the amplitude. 

$$
I_{observed} \propto |E_{r}(x,t) + E_{s}(x,t)|^2
$$

We know that the squared amplitude of a complex number is the complex number multiplied by its conjugate.

$$
|e^{i \theta}|^2 = e^{i \theta} * e^{i -\theta}
$$

We can apply this principle to the squared amplitude of the superposition of the sample and reference wave.

$$
|E_{r}(x,t) + E_{s}(x,t)|^2 = |E_{1}e^{(k_{1}x - w_{1}t + \phi_{1})} + E_{2}e^{(k_{2}x - w_{2}t + \phi_{2})}|^2
$$

$$
= (E_{1}e^{(k_{1}x - w_{1}t + \phi_{1})} + E_{2}e^{(k_{2}x - w_{2}t + \phi_{2})})(E_{1}e^{-(k_{1}x - w_{1}t + \phi_{1})} + E_{2}e^{-(k_{2}x - w_{2}t + \phi_{2})})
$$

$$
= E_{1}e^{(k_{1}x - w_{1}t) + \phi_{1}}E_{1}e^{-(k_{1}x - w_{1}t + \phi_{1})} + E_{2}e^{(k_{2}x - w_{2}t + \phi_{2})}E_{2}e^{-(k_{2}x - w_{2}t + \phi_{2})} + E_{1}e^{(k_{1}x - w_{1}t) + \phi_{1}}E_{2}e^{-(k_{2}x - w_{2}t + \phi_{2})} + E_{1}e^{-(k_{1}x - w_{1}t + \phi_{1})}E_{2}e^{(k_{2}x - w_{2}t + \phi_{2})}
$$

$$
= E_{1}^2 + E_{2}^2 + E_{1}E_{2}e^{i[(k_{1}-k_{2})x + (w_{1}-w_{2})t + (\phi_{1}-\phi_{2})]} + E_{1}E_{2}e^{-i[(k_{1}-k_{2})x + (w_{1}-w_{2})t + (\phi_{1}-\phi_{2})]}
$$

$$
= E_{1}^2 + E_{2}^2 + E_{1}E_{2}[e^{i[(k_{1}-k_{2})x + (w_{1}-w_{2})t + (\phi_{1}-\phi_{2})]} + e^{-i[(k_{1}-k_{2})x + (w_{1}-w_{2})t + (\phi_{1}-\phi_{2})]}]
$$

From here we can simplify using Euler's Identity...

$$
cos(\theta) = \frac{e^{i \theta} + e{-i \theta}}{2}
$$

or more useful for our purposes:

$$
2cos(\theta) = e^{i \theta} + e{-i \theta}
$$

We can then simplify the interference equation as such:

$$
= E_{1}^2 + E_{2}^2 + 2E_{1}E_{2}cos(\Delta x + \Delta w t + \Delta \phi)
$$

We know that the intensity of the reference beam and the sample beam are proportional to the squared amplitude of the respective waves:

$$
I_{r} \propto |E_{1}e^{(k_{1}x - w_{1}t + \phi_{1})}|^2 = E_{1}^2
$$

$$
I_{s} \propto |E_{2}e^{(k_{2}x - w_{2}t + \phi_{2})}|^2 = E_{2}^2
$$

And as such we can write the final interference intensity equation in terms of the intensities of the reference and sample beam respectively:

$$
I_{observed}= I_{r} + I_{s} + 2\sqrt{I_{r}I_{s}}cos(\Delta x + \Delta w t + \Delta \phi)
$$

## 5.3 Appendix C: Electrical Optical Modulator (EOM) Setup and Results
Before implementing the low coherence interferometry (LCI) setup, a Michelson interferometry setup was used, where an electro-optic modulator (EOM) was used to alter the path length of the reference beam. This setup allowed for more sensitive measurements than directing the laser straight into the Arabidopsis root, but hypersensitivity of the setup became an issue as air flow and minute movement of the table the setup rested on were enough to interfere with the EOM setup. We saw this in large variations in data over different trials at the same input voltage (see @fig-eom).

![The output interference signal of two different trials of the same input voltage into the EOM over multiple sweeps of input voltages showcase a large variance of the output signal among trials. The inability to map the voltage signal to a unique input voltage rendered the EOM setup unusable from the sensitivity.](eomdata.png){#fig-eom}

The low-coherence interferometry setup was purused in the prospects of greater stability. 